{{ if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "leaksignal.name" . }}
  labels:
    app: {{ include "leaksignal.name" . }}
    {{- include "leaksignal.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "leaksignal.name" . }}
  labels:
    app: {{ include "leaksignal.name" . }}
    {{- include "leaksignal.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs:
  - list
  - get
  - delete
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - list
  - get
  - patch
  - update
- apiGroups:
  - leaksignal.com
  resources:
  - cluster-leaksignal-istios
  - leaksignal-istios
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "leaksignal.name" . }}
  labels:
    app: {{ include "leaksignal.name" . }}
    {{- include "leaksignal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "leaksignal.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "leaksignal.name" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}