---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: leaksignal
  namespace: istio-system
spec:
  configPatches:
  - applyTo: EXTENSION_CONFIG
    match:
      context: ANY
    patch:
      operation: ADD
      value:
        name: leaksignal-proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            name: "leaksignal"
            root_id: "leaksignal"
            configuration:
              "@type": type.googleapis.com/google.protobuf.StringValue
              value: |
                  local_policy:
                    categories:
                      ssn:
                        Matchers:
                          regexes:
                            - "(?!(\\d){3}(-| |)\\1{2}\\2\\1{4})(?!666|000|9\\d{2})(\\b\\d{3}(-| |)(?!00)\\d{2}\\4(?!0{4})\\d{4}\\b)"
                      credit_card:
                        Matchers:
                          regexes:
                            - "\\d{16}"
                            - "\\d{4}[\\s.-]\\d{4}[\\s.-]\\d{4}[\\s.-]\\d{4}"
                            - "(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})"
                          ignore:
                            - 0000-0000-0000-0000
                      email:
                        Matchers:
                          regexes:
                            - "[a-zA-Z0-9_.+-]{2,}@[a-zA-Z0-9-]{3,}\\.[a-zA-Z0-9-.]{2,}"
                          ignore:
                            - someone@example.com
                      phone_number:
                        Matchers:
                          regexes:
                            - "[^0-9](?:\\+1[\\s.-])?(?:\\d{3}|\\(\\d{3}\\))[\\s.-]\\d{3}[\\s.-]\\d{4}[^0-9]"
                      address:
                        Matchers:
                          regexes:
                            - "(?i)[0-9]+[a-zà-ú.,-]* ((highway)|(autoroute)|(north)|(nord)|(south)|(sud)|(east)|(est)|(west)|(ouest)|(avenue)|(lane)|(voie)|(ruelle)|(road)|(rue)|(route)|(drive)|(boulevard)|(circle)|(cercle)|(street)|(cer\\.?)|(cir\\.?)|(blvd\\.?)|(hway\\.?)|(st\\.?)|(aut\\.?)|(ave\\.?)|(ln\\.?)|(rd\\.?)|(hw\\.?)|(dr\\.?))([ .,-]*[a-zà-ú0-9]*)*"
                      phone_number_correlate:
                        Correlate:
                          group1:
                            regexes:
                              - "[^0-9][0-9]{10}[^0-9]"
                            regex_strip: 1
                          group2:
                            raw:
                              - phone
                          interest: group1
                          max_distance: 64
                      date_of_birth:
                        Correlate:
                          group1:
                            regexes:
                              - "[^0-9][0-9]{1,2}[/-][0-9]{1,2}[/-][0-9]{2,4}[^0-9]"
                            regex_strip: 1
                          group2:
                            raw:
                              - dob
                              - date_of_birth
                              - birth_date
                          interest: group1
                          max_distance: 24
                      name_key:
                        Matchers:
                          raw:
                            - first_name
                            - last_name
                            - full_name
                      access_token_key:
                        Matchers:
                          raw:
                            - access_token
                    endpoints:
                      - matches: "**"
                        config:
                          # json keys
                          name_key:
                            contexts: keys
                            content_types: json
                          access_token_key:
                            contexts: keys
                            content_types: json
                          # end json keys
                          credit_card:
                            report_style: partial_sha256
                            report_bits: 32
                          ssn:
                            report_style: partial_sha256
                            report_bits: 24
                          email: {}
                          phone_number: {}
                          address: {}
                          date_of_birth: {}
                          email: {}
                          address: {}
                          phone_number_correlate: {}
                      - matches: "*/product/*"
                      - matches: "*/cart"
                      - matches: "*/cart/checkout"
                    body_collection_rate: 0.0
                    report_style: raw
            vm_config:
              runtime: "envoy.wasm.runtime.v8"
              vm_id: "leaksignal_proxy"
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: leaksignal-proxy
        config_discovery:
          config_source:
            ads: {}
          type_urls: ["type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"]
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: leaksignal-upstream
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: ADD
      value:
        name: leaksignal_infra
        type: STRICT_DNS
        http2_protocol_options: {}
        dns_lookup_family: V4_PREFERRED
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: leaksignal_infra0
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ingestion.app.leaksignal.com
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: ingestion.app.leaksignal.com
            common_tls_context:
              validation_context:
                match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: ingestion.app.leaksignal.com
                trusted_ca:
                  filename: /etc/ssl/certs/ca-certificates.crt
