policies:
  example:
    categories:
      bank_routing_us:
        Matchers:
          - regex: "(?-u:\\b)(0[0-9]|11|12|2[1-9]|30|31|32|6[1-9]|70|71|72|80)\\d{7}(?-u:\\b)"
          - and:
            - internal: routing_number
    endpoints:
      - matches: "**"
        config:
          bank_routing_us: {}
