---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: leaksignal
spec:
  configPatches:
  - applyTo: EXTENSION_CONFIG
    match:
      context: ANY
    patch:
      operation: ADD
      value:
        name: leaksignal-proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            name: "leaksignal"
            root_id: "leaksignal"
            configuration:
              "@type": type.googleapis.com/google.protobuf.StringValue
              value: |
                upstream_cluster: leaksignal_infra
                upstream_host: leakagent.leakagent.svc.cluster.local:8121
                api_key: example
            vm_config:
              runtime: "envoy.wasm.runtime.v8"
              vm_id: "leaksignal_proxy"
              environment_variables:
                host_env_keys:
                - HOSTNAME
                - POD_NAME
                - INSTANCE_IP
                - ISTIO_META_WORKLOAD_NAME
                - ISTIO_META_MESH_ID
                - TRUST_DOMAIN
                - POD_NAMESPACE
                - SERVICE_ACCOUNT
              code:
                remote:
                  http_uri:
                    uri: http://leakagent.leakagent.svc.cluster.local:8121/proxy/2023_09_28_20_39_42_346bda6_0.7.1/leaksignal.wasm
                    timeout: 10s
                    cluster: leaksignal_infra
                  sha256: 7009da43730297de3f8fafbf23df51b593b9e3f18cb33e3298b840a9e6c54c32
                  retry_policy:
                    num_retries: 10
  - applyTo: HTTP_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: leaksignal-proxy
        config_discovery:
          config_source:
            ads: {}
          type_urls: ["type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm"]
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: ADD
      value:
        name: leaksignal_infra
        type: STRICT_DNS
        http2_protocol_options: {}
        dns_lookup_family: V4_PREFERRED
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: leaksignal_infra0
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: leakagent.leakagent.svc.cluster.local
                    port_value: 8121
