apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: leakagent

resources:
- ./leakagent.yaml
configMapGenerator:
- name: leakagent-config
  namespace: leakagent
  files:
  - config.yaml
  options:
    disableNameSuffixHash: true
