apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: leaksignal-operator.0.3.1
  annotations:
    capabilities: Full Lifecycle
    categories: Security
    containerImage: docker.io/leaksignal/leaksignal-operator:0.3.1
    createdAt: '2024-01-31T00:00:00Z'
    support: LeakSignal Inc. https://leaksignal.com
    description: Install LeakSignal in seconds with the LeakSignal Operator.
    repository: https://github.com/leaksignal/leaksignal
    certified: 'false'
    alm-examples: |
      [
        {
          "apiVersion": "leaksignal.com/v1",
          "kind": "LeaksignalIstio",
          "metadata": {
            "name": "leaksignal-istio"
          },
          "spec": {
            "proxyHash": "fcecd3a3b099bebb432cf78e48c6f3f24a7d71b92e06b75ba5301877554960ff",
            "proxyVersion": "2024_01_29_22_53_36_5a454f0_0.9.5",
            "apiKey": "example",
          }
        },
        {
          "apiVersion": "leaksignal.com/v1",
          "kind": "ClusterLeaksignalIstio",
          "metadata": {
            "name": "leaksignal-istio"
          },
          "spec": {
            "proxyHash": "fcecd3a3b099bebb432cf78e48c6f3f24a7d71b92e06b75ba5301877554960ff",
            "proxyVersion": "2024_01_29_22_53_36_5a454f0_0.9.5",
            "apiKey": "example",
          }
        }
      ]
spec:
  description: Install LeakSignal in seconds with the LeakSignal Operator.
  displayName: LeakSignal Operator
  keywords:
  - leaksignal
  - istio
  - wasm
  maintainers:
  - email: max@leaksignal.com
    name: Max Bruce
  maturity: stable
  provider:
    name: LeakSignal
    url: leaksignal.com
  links:
  - name: Documentation
    url: https://www.leaksignal.com/docs/Operator/Getting%20Started
  version: 0.3.1
  customresourcedefinitions:
    owned:
    - name: leaksignal-istios.leaksignal.com
      version: v1
      kind: LeaksignalIstio
    - name: cluster-leaksignal-istios.leaksignal.com
      version: v1
      kind: ClusterLeaksignalIstio
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - rules:
        - apiGroups: [""]
          resources:
          - namespaces
          - pods
          verbs:
          - list
          - get
          - delete
        - apiGroups: ["apps"]
          resources:
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - list
          - get
          - patch
          - update
        - apiGroups:
          - leaksignal.com
          resources:
          - cluster-leaksignal-istios
          - leaksignal-istios
          verbs:
          - get
          - watch
          - list
          - patch
        - apiGroups:
          - networking.istio.io
          resources:
          - envoyfilters
          verbs:
          - get
          - watch
          - list
          - create
          - update
          - patch
          - delete
        serviceAccountName: leaksignal-operator
      deployments:
      - name: leaksignal-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: leaksignal-operator
          template:
            metadata:
              labels:
                app: leaksignal-operator
            spec:
              containers:
              - name: leaksignal-operator
                image: leaksignal/leaksignal-operator:1.3.1
                imagePullPolicy: "Always"
              serviceAccountName: leaksignal-operator
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces