apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
  name: leaksignal-operator.0.3.1
spec:
  description: This is an operator for LeakSignal.
  displayName: LeakSignal Operator
  keywords:
  - leaksignal
  maintainers:
  - email: max@leaksignal.com
    name: Max Bruce
  maturity: stable
  provider:
    name: LeakSignal
    url: leaksignal.com
  version: 0.3.1
  customresourcedefinitions:
    owned:
    - name: leaksignal-istios.leaksignal.com
      version: v1
      kind: LeaksignalIstio
    - name: cluster-leaksignal-istios.leaksignal.com
      version: v1
      kind: ClusterLeaksignalIstio
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - rules:
        - apiGroups: [""]
          resources:
          - namespaces
          - pods
          verbs:
          - list
          - get
          - delete
        - apiGroups: ["apps"]
          resources:
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - list
          - get
          - patch
          - update
        - apiGroups:
          - leaksignal.com
          resources:
          - cluster-leaksignal-istios
          - leaksignal-istios
          verbs:
          - get
          - watch
          - list
          - patch
        - apiGroups:
          - networking.istio.io
          resources:
          - envoyfilters
          verbs:
          - get
          - watch
          - list
          - create
          - update
          - patch
          - delete
        serviceAccountName: leaksignal-operator
      deployments:
      - name: leaksignal-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: leaksignal-operator
          template:
            metadata:
              labels:
                app: leaksignal-operator
            spec:
              containers:
              - name: leaksignal-operator
                image: leaksignal/leaksignal-operator:1.3.1
                imagePullPolicy: "Always"
              serviceAccountName: leaksignal-operator
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces