apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leaksignal.fullname" . }}-leakagent
  labels:
    app: leakagent
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: leakagent
      {{- include "leaksignal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: leakagent
        {{- include "leaksignal.labels" . | nindent 8 }}
    spec:
      volumes:
      - name: leakagent-config
        configMap:
          {{ if .Values.config_name }}
          name: {{ .Values.config_name }}
          {{ else }}
          name: {{ include "leaksignal.fullname" . }}-config
          {{ end }}
      containers:
      - name: leakagent
        image: leaksignal/leakagent:{{- .Chart.AppVersion }}
        env:
        - name: LS_CONFIG_PATH
          value: /config/config.yaml
        imagePullPolicy: Always
        ports:
        - name: ingestion
          containerPort: 8121
        - name: prometheus
          containerPort: 9176
        volumeMounts:
        - name: leakagent-config
          mountPath: /config/
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "leaksignal.fullname" . }}-leakagent
  labels:
    app: leakagent
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  selector:
    app: leakagent
    {{- include "leaksignal.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8121
      targetPort: 8121
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "leaksignal.fullname" . }}-leakagent-prom
  labels:
    app: leakagent
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  selector:
    app: leakagent
    {{- include "leaksignal.selectorLabels" . | nindent 4 }}
  ports:
    - name: prometheus
      protocol: TCP
      port: 9176
      targetPort: 9176

{{ if .Values.prometheus_operator }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "leaksignal.fullname" . }}-leakagent
  labels:
    app: leakagent
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: leakagent
      {{- include "leaksignal.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: prometheus
    interval: {{ .Values.prometheus_operator.scrape_interval }}
{{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leaksignal.fullname" . }}-config
  labels:
    app: leakagent
    {{- include "leaksignal.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config/*").AsConfig | indent 2 }}
