{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "leaksignal.fullname" . }}-metrics
  labels:
    app: leakagent
    {{- include "leaksignal.labels" . | nindent 4 }}
    {{- with .Values.metricsService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if (or (eq .Values.metricsService.type "ClusterIP") (empty .Values.metricsService.type)) }}
  type: ClusterIP
  {{- with .Values.metricsService.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- else if eq .Values.metricsService.type "LoadBalancer" }}
  type: {{ .Values.metricsService.type }}
  {{- with .Values.metricsService.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.metricsService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
  type: {{ .Values.metricsService.type }}
  {{- end }}
  {{- with .Values.metricsService.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: prometheus
      port: 9176
      protocol: TCP
      targetPort: 9176
      {{- if (and (eq .Values.metricsService.type "NodePort") (not (empty .Values.metricsService.nodePort))) }}
      nodePort: {{ .Values.metricsService.nodePort }}
      {{- end }}
  selector:
    app: leakagent
    {{- include "leaksignal.selectorLabels" . | nindent 4 }}
{{- end }}
