{
 "title": "LeakSignal Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(leaksignal_request_time_ms_bucket, deployment)"
    }
   },
   {
    "name": "service",
    "label": "Services",
    "query": {
     "query": "label_values(leaksignal_request_time_ms_bucket{deployment=\"$deployment\"}, local_service)"
    }
   },
   {
    "name": "policy_path",
    "label": "Policy Path",
    "query": {
     "query": "label_values(leaksignal_request_time_ms_bucket{deployment=\"$deployment\", local_service=~\"$service\",  is_outbound=\"true\"}, policy_path)"
    }
   },
   {
    "name": "pvalue",
    "label": "Percentile",
    "query": "p99 : 0.99, p95 : 0.95,p90 : 0.90,p75 : 0.75,p50 : 0.50,p25 : 0.25,p10 : 0.10,p5 : 0.05, p1 : 0.01"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (local_service, policy_path, status)(irate(leaksignal_status_code{deployment=\"$deployment\",local_service=~\"$service\",policy_path=~\"$policy_path\",is_outbound=\"true\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leaksignal Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($pvalue, sum by (local_service, policy_path, le)(rate(leaksignal_match_time_ms_bucket{deployment=\"$deployment\",local_service=~\"$service\",policy_path=~\"$policy_path\",is_outbound=\"true\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($pvalue, sum by (local_service, policy_path, le)(rate(leaksignal_request_time_ms_bucket{deployment=\"$deployment\",local_service=~\"$service\",policy_path=~\"$policy_path\",is_outbound=\"true\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($pvalue, sum by (local_service, policy_path, le)(rate(leaksignal_response_time_ms_bucket{deployment=\"$deployment\",local_service=~\"$service\",policy_path=~\"$policy_path\",is_outbound=\"true\"}[$__rate_interval])))\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  }
 ]
}