{
 "title": "LeakSignal",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(leaksignal_request_time_ms_bucket, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status)(irate(leaksignal_status_code{deployment=\"$deployment\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (local_service, le)(rate(leaksignal_request_time_ms_bucket{deployment=\"$deployment\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (local_service, le)(irate(leaksignal_request_size_bytes_sum{deployment=\"$deployment\"}[$__rate_interval]))/sum by (local_service, le)(irate(leaksignal_request_size_bytes_count{deployment=\"$deployment\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (local_service, le)(rate(leaksignal_response_time_ms_bucket{deployment=\"$deployment\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (local_service, le)(irate(leaksignal_response_size_bytes_sum{deployment=\"$deployment\"}[$__rate_interval]))/sum by (local_service, le)(irate(leaksignal_response_size_bytes_count{deployment=\"$deployment\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leaksignal Timing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(leaksignal_match_time_ms_bucket{deployment=\"$deployment\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}