{
 "title": "LeakAgent",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(leakagent_match_inbound[$__rate_interval]))",
     "legendFormat": "Requests per Second"
    }
   ]
  },
  {
   "title": "WASM Pulls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(leakagent_proxy_pull[$__rate_interval]))",
     "legendFormat": "Requests per Second"
    }
   ]
  },
  {
   "title": "Policy Dispatch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (policy)(irate(leakagent_policy_update_send[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Node Connections by Policy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (policy)(irate(leakagent_policy_update_init[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently Connected Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Nodes" } },
   "targets": [
    {
     "expr": "sum by (deployment)(leakagent_policy_update_waiting)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Turned Away Node Connections by Policy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (policy)(irate(leakagent_policy_update_turnaway[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}